



INSERT INTO public.form_l_titulares(
            searchtext, found_party, parent_key, key_test)
  

SELECT DISTINCT
  "LEGEND_L_V2_TITULARES"."SEARCHTEXT", 
  "LEGEND_L_V2_TITULARES"."FOUND_PARTY", 
  "LEGEND_L_V2_TITULARES"."_PARENT_AURI",
   concat("LEGEND_L_V2_TITULARES"."SEARCHTEXT"||"LEGEND_L_V2_TITULARES"."FOUND_PARTY"||"LEGEND_L_V2_TITULARES"."_PARENT_AURI")as key_test
FROM 
  odk_prod."LEGEND_L_V2_TITULARES"

WHERE concat("LEGEND_L_V2_TITULARES"."SEARCHTEXT"||"LEGEND_L_V2_TITULARES"."FOUND_PARTY"||"LEGEND_L_V2_TITULARES"."_PARENT_AURI") not in (SELECT key_test FROM form_l_titulares) AND
"LEGEND_L_V2_TITULARES"."FOUND_PARTY" != '1'


INSERT INTO public.form_l_testemunhas_v2(
            search_text, found_testem, testem_type, parent_uid, key)

SELECT DISTINCT 
  "LEGEND_L_V2_TESTEMUNHAS"."SEARCHTEXT_3", 
  "LEGEND_L_V2_TESTEMUNHAS"."FOUND_TESTEM", 
  "LEGEND_L_V2_TESTEMUNHAS"."TESTEM_TYPE", 
  "LEGEND_L_V2_TESTEMUNHAS"."_PARENT_AURI",
concat("LEGEND_L_V2_TESTEMUNHAS"."FOUND_TESTEM"||"LEGEND_L_V2_TESTEMUNHAS"."_PARENT_AURI") as key
FROM 
odk_prod."LEGEND_L_V2_TESTEMUNHAS"
WHERE (concat("LEGEND_L_V2_TESTEMUNHAS"."FOUND_TESTEM"||"LEGEND_L_V2_TESTEMUNHAS"."_PARENT_AURI")  NOT IN (SELECT key FROM form_l_testemunhas_v2))AND 
"LEGEND_L_V2_TESTEMUNHAS"."FOUND_TESTEM" != '1'