INSERT INTO public.form_l_testemunhas_v2(
            search_text, found_testem, testem_type, parent_uid, key)

SELECT DISTINCT 
  "LEGEND_L_V2_TESTEMUNHAS"."SEARCHTEXT_3", 
  "LEGEND_L_V2_TESTEMUNHAS"."FOUND_TESTEM", 
  "LEGEND_L_V2_TESTEMUNHAS"."TESTEM_TYPE", 
  "LEGEND_L_V2_TESTEMUNHAS"."_PARENT_AURI",
concat("LEGEND_L_V2_TESTEMUNHAS"."FOUND_TESTEM"||"LEGEND_L_V2_TESTEMUNHAS"."_PARENT_AURI") as key
FROM 
odk_prod."LEGEND_L_V2_TESTEMUNHAS"
WHERE (concat("LEGEND_L_V2_TESTEMUNHAS"."FOUND_TESTEM"||"LEGEND_L_V2_TESTEMUNHAS"."_PARENT_AURI")  NOT IN (SELECT key FROM form_l_testemunhas_v2))AND 
"LEGEND_L_V2_TESTEMUNHAS"."FOUND_TESTEM" != '1'







INSERT INTO public.form_l_novas_pessoas(
            app, nom, role, gen, civil, prof, nacion, naturalidade, 
            nascyn, nasc, aida, doc, doc_id, localidade, emi, val, vital, 
            foto, idfoto, assin, contacto, parentuid, party_name, party_name_key, 
            key_test )
SELECT 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_APP" as app, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_NOM" as nom,
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_NOM" as role,
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_GEN" as gen, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_CIVIL" as civil, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."TESTEM_PROF" as prof, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG6_TESTEM_NACION" as nacion, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG6_TESTEM_NATURAL" as naturalidade, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."TESTEM_NASC_Y_N" as nascyn, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."TESTEM_NASC":: date as nasc, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."TESTEM_IDA" as aida, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC" as doc, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_ID" as doc_id, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC_LOCAL" as local, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC_EMI"::date as emi, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC_VAL"::date as val, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC_VITAL" as vital,
  concat('<img src="http://tfmoz.ddns.net/legend/media/'||"LEGEND_L_V2_TESTEM_FOTO_BN"."UNROOTED_FILE_PATH"||'" style="width:1024px;height:1024px;" />')::text as pessoafoto,
  concat('<img src="http://tfmoz.ddns.net/legend/media/'||"LEGEND_L_V2_TESTEM_ID_FOTO_BN"."UNROOTED_FILE_PATH"||'" style="width:1024px;height:1024px;" />')::text as idfoto,
  concat('<img src="http://tfmoz.ddns.net/legend/media/'||"LEGEND_L_V2_TESTEM_ASSIN_BN"."UNROOTED_FILE_PATH"||'" style="width:1024px;height:1024px;" />')::text as assin,
  "LEGEND_L_V2_NOVAS_PESSOAS1"."TESTEM_CONTACTO" as contacto, 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."_PARENT_AURI" as parentuid,
CONCAT("LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_APP"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_NOM"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_ID") AS party_name,
CONCAT("LEGEND_L_V2_NOVAS_PESSOAS1"."_PARENT_AURI"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_APP"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_NOM"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_ID") as party_name_key,
CONCAT("LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_APP"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_NOM"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_ID") AS key_test

FROM 
  odk_prod."LEGEND_L_V2_NOVAS_PESSOAS1", 
  odk_prod."LEGEND_L_V2_CORE",
  odk_prod."LEGEND_L_V2_TESTEM_FOTO_BN", 
  odk_prod."LEGEND_L_V2_TESTEM_ID_FOTO_BN", 
  odk_prod."LEGEND_L_V2_TESTEM_ASSIN_BN"
WHERE 
  "LEGEND_L_V2_NOVAS_PESSOAS1"."_PARENT_AURI" = "LEGEND_L_V2_CORE"."_URI" AND
  "LEGEND_L_V2_NOVAS_PESSOAS1"."_URI" = "LEGEND_L_V2_TESTEM_ID_FOTO_BN"."_PARENT_AURI" AND
  "LEGEND_L_V2_TESTEM_FOTO_BN"."_PARENT_AURI" = "LEGEND_L_V2_NOVAS_PESSOAS1"."_URI" AND
  "LEGEND_L_V2_TESTEM_ASSIN_BN"."_PARENT_AURI" = "LEGEND_L_V2_NOVAS_PESSOAS1"."_URI" AND
  CONCAT("LEGEND_L_V2_NOVAS_PESSOAS1"."_PARENT_AURI"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_APP"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_NOM"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC"||"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_ID") NOT IN (SELECT party_name_key FROM form_l_novas_pessoas) ;