

SELECT "_URI"
FROM odk_prod."LEGEND_L_V2_CORE",
form_l_registrar_parcela  
WHERE "LEGEND_L_V2_CORE"."_URI" = key







SELECT "LEGEND_L_V2_CORE"."_URI"
  FROM odk_prod."LEGEND_L_V2_CORE",
odk_prod.legend_restored_cor
WHERE "LEGEND_L_V2_CORE"."_URI"  = legend_restored_cor."_URI";








SELECT 
"LEGEND_L_V2_LG2_PESSOA_ROLE"."_URI", 
"LEGEND_L_V2_LG2_PESSOA_ROLE"."_CREATOR_URI_USER", 
"LEGEND_L_V2_LG2_PESSOA_ROLE"."_CREATION_DATE", 
"LEGEND_L_V2_LG2_PESSOA_ROLE"."_LAST_UPDATE_URI_USER", 
"LEGEND_L_V2_LG2_PESSOA_ROLE"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_LG2_PESSOA_ROLE"."_PARENT_AURI", 
"LEGEND_L_V2_LG2_PESSOA_ROLE"."_ORDINAL_NUMBER", 
"LEGEND_L_V2_LG2_PESSOA_ROLE"."_TOP_LEVEL_AURI", 
"LEGEND_L_V2_LG2_PESSOA_ROLE"."VALUE"
  
FROM 
odk_prod."LEGEND_L_V2_LG2_PESSOA_ROLE",
odk_prod.legend_restored_cor

WHERE 
"LEGEND_L_V2_LG2_PESSOA_ROLE"."_TOP_LEVEL_AURI"  = legend_restored_cor."_URI";

SELECT "LEGEND_L_V2_NOVAS_PESSOAS"."_URI", 
"LEGEND_L_V2_NOVAS_PESSOAS"."_CREATOR_URI_USER", 
"LEGEND_L_V2_NOVAS_PESSOAS"."_CREATION_DATE", 
"LEGEND_L_V2_NOVAS_PESSOAS"."_LAST_UPDATE_URI_USER", 
"LEGEND_L_V2_NOVAS_PESSOAS"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_NOVAS_PESSOAS"."_PARENT_AURI", 
"LEGEND_L_V2_NOVAS_PESSOAS"."_ORDINAL_NUMBER", 
"LEGEND_L_V2_NOVAS_PESSOAS"."_TOP_LEVEL_AURI", 
"LEGEND_L_V2_NOVAS_PESSOAS"."LG4_PESSOA_DOC", 
"LEGEND_L_V2_NOVAS_PESSOAS"."LG4_DOC_VITAL", 
"LEGEND_L_V2_NOVAS_PESSOAS"."LG2_PESSOA_NOM", 
"LEGEND_L_V2_NOVAS_PESSOAS"."LG4_DOC_EMI", 
"LEGEND_L_V2_NOVAS_PESSOAS"."PESSOA_PROF_OTHER", 
"LEGEND_L_V2_NOVAS_PESSOAS"."LG2_PESSOA_CIVIL", 
"LEGEND_L_V2_NOVAS_PESSOAS"."LG2_PESSOA_GEN", 
"LEGEND_L_V2_NOVAS_PESSOAS"."PESSOA_PROF", 
"LEGEND_L_V2_NOVAS_PESSOAS"."LG3_PESSOA_NATURAL", 
"LEGEND_L_V2_NOVAS_PESSOAS"."PESSOA_NASC", 
"LEGEND_L_V2_NOVAS_PESSOAS"."CONTACTO", 
"LEGEND_L_V2_NOVAS_PESSOAS"."LG4_PESSOA_ID", 
"LEGEND_L_V2_NOVAS_PESSOAS"."LG4_DOC_VAL", 
"LEGEND_L_V2_NOVAS_PESSOAS"."LG3_PESSOA_NACION", 
"LEGEND_L_V2_NOVAS_PESSOAS"."NASC_Y_N", 
"LEGEND_L_V2_NOVAS_PESSOAS"."PESSOA_IDA", 
"LEGEND_L_V2_NOVAS_PESSOAS"."LG4_DOC_LOCAL", 
"LEGEND_L_V2_NOVAS_PESSOAS"."LG2_PESSOA_APP"

FROM odk_prod."LEGEND_L_V2_NOVAS_PESSOAS",
        odk_prod.legend_restored_cor
WHERE "LEGEND_L_V2_NOVAS_PESSOAS"."_TOP_LEVEL_AURI"  = legend_restored_cor."_URI";


copy (SELECT 
"LEGEND_L_V2_NOVAS_PESSOAS1"."_URI", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."_CREATOR_URI_USER", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."_CREATION_DATE", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."_LAST_UPDATE_URI_USER", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."_PARENT_AURI", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."_ORDINAL_NUMBER", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."_TOP_LEVEL_AURI", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC_EMI", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."TESTEM_NASC_Y_N", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."TESTEM_IDA", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."TESTEM_PROF_OTHER", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."TESTEM_CONTACTO", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_APP", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."TESTEM_NASC", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_GEN", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."LG6_TESTEM_NATURAL", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC_VAL", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC_LOCAL", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_ID", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_CIVIL", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."LG7_TESTEM_DOC_VITAL", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."LG5_TESTEM_NOM", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."LG6_TESTEM_NACION", 
"LEGEND_L_V2_NOVAS_PESSOAS1"."TESTEM_PROF"
FROM odk_prod."LEGEND_L_V2_NOVAS_PESSOAS1",
odk_prod.legend_restored_cor
WHERE "LEGEND_L_V2_NOVAS_PESSOAS1"."_TOP_LEVEL_AURI"  = legend_restored_cor."_URI") to
'/var/lib/share/projects/legend/Working_Folder/LEGEND_L_V2_NOVAS_PESSOAS1.csv' DELIMITER ',' NULL AS '' CSV HEADER ENCODING 'latin1';




SELECT 
"LEGEND_L_V2_PESSOA_ASSIN_BLB"."_URI", 
"LEGEND_L_V2_PESSOA_ASSIN_BLB"."_CREATOR_URI_USER", 
"LEGEND_L_V2_PESSOA_ASSIN_BLB"."_CREATION_DATE", 
"LEGEND_L_V2_PESSOA_ASSIN_BLB"."_LAST_UPDATE_URI_USER", 
"LEGEND_L_V2_PESSOA_ASSIN_BLB"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_PESSOA_ASSIN_BLB"."_TOP_LEVEL_AURI", 
"LEGEND_L_V2_PESSOA_ASSIN_BLB"."VALUE"
  
FROM 
odk_prod."LEGEND_L_V2_PESSOA_ASSIN_BLB",
odk_prod.legend_restored_cor

WHERE 
"LEGEND_L_V2_PESSOA_ASSIN_BLB"."_TOP_LEVEL_AURI"  = legend_restored_cor."_URI";

SELECT 
"LEGEND_L_V2_PESSOA_ASSIN_BN"."_URI", 
"LEGEND_L_V2_PESSOA_ASSIN_BN"."_CREATOR_URI_USER", 
"LEGEND_L_V2_PESSOA_ASSIN_BN"."_CREATION_DATE", 
"LEGEND_L_V2_PESSOA_ASSIN_BN"."_LAST_UPDATE_URI_USER",
"LEGEND_L_V2_PESSOA_ASSIN_BN"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_PESSOA_ASSIN_BN"."_PARENT_AURI", 
"LEGEND_L_V2_PESSOA_ASSIN_BN"."_ORDINAL_NUMBER", 
"LEGEND_L_V2_PESSOA_ASSIN_BN"."_TOP_LEVEL_AURI",
"LEGEND_L_V2_PESSOA_ASSIN_BN"."UNROOTED_FILE_PATH", 
"LEGEND_L_V2_PESSOA_ASSIN_BN"."CONTENT_TYPE", 
"LEGEND_L_V2_PESSOA_ASSIN_BN"."CONTENT_LENGTH", 
"LEGEND_L_V2_PESSOA_ASSIN_BN"."CONTENT_HASH"
  
FROM 
odk_prod."LEGEND_L_V2_PESSOA_ASSIN_BN",
odk_prod.legend_restored_cor

WHERE 
"LEGEND_L_V2_PESSOA_ASSIN_BN"."_TOP_LEVEL_AURI"  = legend_restored_cor."_URI";



SELECT 
"LEGEND_L_V2_PESSOA_ASSIN_REF"."_URI", 
"LEGEND_L_V2_PESSOA_ASSIN_REF"."_CREATOR_URI_USER", 
"LEGEND_L_V2_PESSOA_ASSIN_REF"."_CREATION_DATE", 
"LEGEND_L_V2_PESSOA_ASSIN_REF"."_LAST_UPDATE_URI_USER", 
"LEGEND_L_V2_PESSOA_ASSIN_REF"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_PESSOA_ASSIN_REF"."_DOM_AURI", 
"LEGEND_L_V2_PESSOA_ASSIN_REF"."_SUB_AURI", 
"LEGEND_L_V2_PESSOA_ASSIN_REF"."_TOP_LEVEL_AURI",
"LEGEND_L_V2_PESSOA_ASSIN_REF"."PART"
  
FROM 
odk_prod."LEGEND_L_V2_PESSOA_ASSIN_REF",
odk_prod.legend_restored_cor

WHERE 
"LEGEND_L_V2_PESSOA_ASSIN_REF"."_TOP_LEVEL_AURI"  = legend_restored_cor."_URI";

SELECT 
"LEGEND_L_V2_PESSOA_FOTO_BLB"."_URI", 
"LEGEND_L_V2_PESSOA_FOTO_BLB"."_CREATOR_URI_USER", 
"LEGEND_L_V2_PESSOA_FOTO_BLB"."_CREATION_DATE", 
"LEGEND_L_V2_PESSOA_FOTO_BLB"."_LAST_UPDATE_URI_USER", 
"LEGEND_L_V2_PESSOA_FOTO_BLB"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_PESSOA_FOTO_BLB"."_TOP_LEVEL_AURI", 
"LEGEND_L_V2_PESSOA_FOTO_BLB"."VALUE"
  
FROM 
odk_prod."LEGEND_L_V2_PESSOA_FOTO_BLB",
odk_prod.legend_restored_cor

WHERE 
"LEGEND_L_V2_PESSOA_FOTO_BLB"."_TOP_LEVEL_AURI"  = legend_restored_cor."_URI";

SELECT 
"LEGEND_L_V2_PESSOA_FOTO_BN"."_URI", 
"LEGEND_L_V2_PESSOA_FOTO_BN"."_CREATOR_URI_USER", 
"LEGEND_L_V2_PESSOA_FOTO_BN"."_CREATION_DATE", 
"LEGEND_L_V2_PESSOA_FOTO_BN"."_LAST_UPDATE_URI_USER", 
"LEGEND_L_V2_PESSOA_FOTO_BN"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_PESSOA_FOTO_BN"."_PARENT_AURI", 
"LEGEND_L_V2_PESSOA_FOTO_BN"."_ORDINAL_NUMBER", 
"LEGEND_L_V2_PESSOA_FOTO_BN"."_TOP_LEVEL_AURI",
"LEGEND_L_V2_PESSOA_FOTO_BN"."UNROOTED_FILE_PATH", 
"LEGEND_L_V2_PESSOA_FOTO_BN"."CONTENT_TYPE", 
"LEGEND_L_V2_PESSOA_FOTO_BN"."CONTENT_LENGTH", 
"LEGEND_L_V2_PESSOA_FOTO_BN"."CONTENT_HASH"
  
FROM 
odk_prod."LEGEND_L_V2_PESSOA_FOTO_BN",
odk_prod.legend_restored_cor

WHERE 
"LEGEND_L_V2_PESSOA_FOTO_BN"."_TOP_LEVEL_AURI"  = legend_restored_cor."_URI";

COPY (SELECT 
"LEGEND_L_V2_TITULARES"."_URI", 
"LEGEND_L_V2_TITULARES"."_CREATOR_URI_USER", 
"LEGEND_L_V2_TITULARES"."_CREATION_DATE", 
"LEGEND_L_V2_TITULARES"."_LAST_UPDATE_URI_USER",
"LEGEND_L_V2_TITULARES"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_TITULARES"."_PARENT_AURI", 
"LEGEND_L_V2_TITULARES"."_ORDINAL_NUMBER", 
"LEGEND_L_V2_TITULARES"."_TOP_LEVEL_AURI", 
"LEGEND_L_V2_TITULARES"."FOUND_PARTY", 
"LEGEND_L_V2_TITULARES"."SEARCHTEXT"
  FROM odk_prod."LEGEND_L_V2_TITULARES",
       odk_prod.legend_restored_cor
WHERE "LEGEND_L_V2_TITULARES"."_PARENT_AURI"  = legend_restored_cor."_URI") to
'/var/lib/share/projects/legend/Working_Folder/LEGEND_L_V2_TITULARES.csv' DELIMITER ',' NULL AS '' CSV HEADER --ENCODING 'latin1';

COPY (
SELECT 
"LEGEND_L_V2_PONTOS"."_URI", 
"LEGEND_L_V2_PONTOS"."_CREATOR_URI_USER", 
"LEGEND_L_V2_PONTOS"."_CREATION_DATE", 
"LEGEND_L_V2_PONTOS"."_LAST_UPDATE_URI_USER", 
"LEGEND_L_V2_PONTOS"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_PONTOS"."_PARENT_AURI", 
"LEGEND_L_V2_PONTOS"."_ORDINAL_NUMBER", 
"LEGEND_L_V2_PONTOS"."_TOP_LEVEL_AURI",
"LEGEND_L_V2_PONTOS"."UPN_GPS_LIMIT", 
"LEGEND_L_V2_PONTOS"."AUTO_GPS_LIMIT_ACC", 
"LEGEND_L_V2_PONTOS"."AUTO_GPS_LIMIT_LNG", 
"LEGEND_L_V2_PONTOS"."AUTO_GPS_LIMIT_ALT", 
"LEGEND_L_V2_PONTOS"."AUTO_GPS_LIMIT_LAT"
  FROM odk_prod."LEGEND_L_V2_PONTOS",
       odk_prod.legend_restored_cor
WHERE "LEGEND_L_V2_PONTOS"."_TOP_LEVEL_AURI"  = legend_restored_cor."_URI") to
'/var/lib/share/projects/legend/Working_Folder/LEGEND_L_V2_PONTOS.csv' DELIMITER ',' NULL AS '' CSV HEADER --ENCODING 'latin1';

SELECT 
"LEGEND_L_V2_ID_FOTO_REF"."_URI", 
"LEGEND_L_V2_ID_FOTO_REF"."_CREATOR_URI_USER", 
"LEGEND_L_V2_ID_FOTO_REF"."_CREATION_DATE", 
"LEGEND_L_V2_ID_FOTO_REF"."_LAST_UPDATE_URI_USER",
"LEGEND_L_V2_ID_FOTO_REF"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_ID_FOTO_REF"."_DOM_AURI", 
"LEGEND_L_V2_ID_FOTO_REF"."_SUB_AURI", 
"LEGEND_L_V2_ID_FOTO_REF"."_TOP_LEVEL_AURI",
"LEGEND_L_V2_ID_FOTO_REF"."PART"

  FROM odk_prod."LEGEND_L_V2_ID_FOTO_REF",
       odk_prod.legend_restored_cor

where "LEGEND_L_V2_ID_FOTO_REF"."_TOP_LEVEL_AURI" = legend_restored_cor."_URI";

SELECT 
"LEGEND_L_V2_ID_FOTO_BN"."_URI", 
"LEGEND_L_V2_ID_FOTO_BN"."_CREATOR_URI_USER", 
"LEGEND_L_V2_ID_FOTO_BN"."_CREATION_DATE", 
"LEGEND_L_V2_ID_FOTO_BN"."_LAST_UPDATE_URI_USER", 
"LEGEND_L_V2_ID_FOTO_BN"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_ID_FOTO_BN"."_PARENT_AURI", 
"LEGEND_L_V2_ID_FOTO_BN"."_ORDINAL_NUMBER", 
"LEGEND_L_V2_ID_FOTO_BN"."_TOP_LEVEL_AURI", 
"LEGEND_L_V2_ID_FOTO_BN"."UNROOTED_FILE_PATH", 
"LEGEND_L_V2_ID_FOTO_BN"."CONTENT_TYPE", 
"LEGEND_L_V2_ID_FOTO_BN"."CONTENT_LENGTH", 
"LEGEND_L_V2_ID_FOTO_BN"."CONTENT_HASH"
  
FROM odk_prod."LEGEND_L_V2_ID_FOTO_BN",
       odk_prod.legend_restored_cor

where "LEGEND_L_V2_ID_FOTO_BN"."_TOP_LEVEL_AURI" = legend_restored_cor."_URI";

SELECT "LEGEND_L_V2_PESSOA_FOTO_REF"."_URI", 
"LEGEND_L_V2_PESSOA_FOTO_REF"."_CREATOR_URI_USER", 
"LEGEND_L_V2_PESSOA_FOTO_REF"."_CREATION_DATE", 
"LEGEND_L_V2_PESSOA_FOTO_REF"."_LAST_UPDATE_URI_USER",
"LEGEND_L_V2_PESSOA_FOTO_REF"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_PESSOA_FOTO_REF"."_DOM_AURI", 
"LEGEND_L_V2_PESSOA_FOTO_REF"."_SUB_AURI", 
"LEGEND_L_V2_PESSOA_FOTO_REF"."_TOP_LEVEL_AURI",
"LEGEND_L_V2_PESSOA_FOTO_REF"."PART"
  
FROM 
odk_prod."LEGEND_L_V2_PESSOA_FOTO_REF",
odk_prod.legend_restored_cor

WHERE 
"LEGEND_L_V2_PESSOA_FOTO_REF"."_TOP_LEVEL_AURI"  = legend_restored_cor."_URI";


SELECT 
"LEGEND_L_V2_ID_FOTO_BLB"."_URI", 
"LEGEND_L_V2_ID_FOTO_BLB"."_CREATOR_URI_USER", 
"LEGEND_L_V2_ID_FOTO_BLB"."_CREATION_DATE", 
"LEGEND_L_V2_ID_FOTO_BLB"."_LAST_UPDATE_URI_USER", 
"LEGEND_L_V2_ID_FOTO_BLB"."_LAST_UPDATE_DATE", 
"LEGEND_L_V2_ID_FOTO_BLB"."_TOP_LEVEL_AURI", 
"LEGEND_L_V2_ID_FOTO_BLB"."VALUE"

  FROM odk_prod."LEGEND_L_V2_ID_FOTO_BLB",
       odk_prod.legend_restored_cor

WHERE "LEGEND_L_V2_ID_FOTO_BLB"."_TOP_LEVEL_AURI" = legend_restored_cor."_URI";
